### ISSUE TITLE
Add social profiles on Founders section

### ISSUE THREAD

**Issue by MihaiAlisie** [ethereum/ethereum.org#10]
It would be nice if we could have social profile links added in the box for each founder

To get things rolling here is a list of Twitter and LinkedIn profiles:

**Vitalik Buterin**
https://twitter.com/VitalikButerin
ca.linkedin.com/pub/vitalik-buterin/50/a74/267/en

**Mihai Alisie**
https://twitter.com/MihaiAlisie
ch.linkedin.com/in/MihaiAlisie

**Anthony Di Iorio**
https://twitter.com/diiorioanthony
ca.linkedin.com/in/anthonydiiorio1/en

**Taylor Gerring**
https://twitter.com/TaylorGerring
www.linkedin.com/in/taylorgerring/en

**Gavin Wood**
https://twitter.com/gavofyork
uk.linkedin.com/pub/gavin-wood/16/433/888/en

**Stephan Tual**
https://twitter.com/stephantual
uk.linkedin.com/in/stephantual/en

**Jeffrey Wilcke**
https://twitter.com/jeffehh
nl.linkedin.com/in/jeffreywilcke/en

**Joseph Lubin**
https://twitter.com/ethereumJoseph
jm.linkedin.com/pub/joseph-lubin/89/64/484/en

**Comment by jesuscript** [comment]
could wrap all bios in {{markdown}}. potential improvement

**Comment by jesuscript** [comment]
right, so all bios now are CMS-editable and support markdown so if we want to add links to social profiles - we can do it. Whether we want to do it or not has no longer anything to do with this repo. Closing.
