### ISSUE TITLE
ethereum.org/whitepaper and ethereum.org/yellowpaper

### ISSUE THREAD

**Issue by MihaiAlisie** [ethereum/ethereum.org#11]
Before we had the ethereum whitepaper at https://www.ethereum.org/pdfs/EthereumWhitePaper.pdf (currently not working) and the yellow paper at http://gavwood.com/Paper.pdf. 

I suggest to have them at ethereum.org/whitepaper and ethereum.org/yellowpaper.

**Comment by jesuscript** [comment]
The yellow paper link is fine. The white paper one will be http://github.com/ethereum/wiki/wiki/White-Paper

**Comment by MihaiAlisie** [comment]
This is what I currently get when going to ethereum.org/yellowpaper

![screen shot 2015-03-01 at 21 07 56](https://cloud.githubusercontent.com/assets/6831213/6432603/5642a1ae-c057-11e4-8825-bbc21e60b38c.png)

Please make the [YellowPaper.pdf](https://files.zenhub.io/54f371fa5db5a65678edee00) accessible on ethereum.org
