### ISSUE TITLE
Bad links 

### ISSUE THREAD

**Issue by awrelll** [ethereum/ethereum.org#12]
-Pokereum points to https://http//www.pokereum.io
-ethergit seems to be down for some time.
-cubespawn points to a subdomain than no longer exists https://main.cubespawn.com/cgi-sys/defaultwebpage.cgi

**Comment by jesuscript** [comment]
Thanks. I believe all of the links are working now. We'll give ethergit a day or two, if it's still down I'll replace it with something else
