### ISSUE TITLE
Remove Pokereum

### ISSUE THREAD

**Issue by jmlubin** [ethereum/ethereum.org#17]
Pokereum should be removed and never should have been there publicly in the first place.  They have a weak white paper and are likely to remain vapor and they are trading on Vitalik's and Jeremie Miller's names ahead of their crowdsale.  Replace it with Airlock or something legit.

**Comment by jesuscript** [comment]
We don't currently have a good reason to do that. George is going to ask them to drop any references to Vitalik from their white paper. If they refuse we'll definitely remove them. Closing the issue for now

**Comment by innovator256** [comment]
What a snake
