### ISSUE TITLE
More blurboids

### ISSUE THREAD

**Issue by jmlubin** [ethereum/ethereum.org#28]
Decentralized applications -- dApps
dApp deployment cost: $0
Monthly dApp hosting services cost: $0
dApp usage costs: micro payment$
Deploying a dApp impervious to censorship: pricele$$
Deploying a radically transparent dApp: pricele$$
Deploying a no-trust-required dApp: pricele$$
Deploying a no-counterparty-risk dApp: pricele$$
An infrastructure for next gen social and economic systems

Konstantin, very nice job, btw.  Thank you.

**Comment by jesuscript** [comment]
Thanks :) relayed these to George
