### ISSUE TITLE
A Platform for Decentralized Applications

### ISSUE THREAD

**Issue by jmlubin** [ethereum/ethereum.org#30]
What happened to the nice, red 
  "A Platform for Decentralized Applications"
text?

Without it, naive surfers will have no idea what Ethereum is.

**Comment by jesuscript** [comment]
We will re-incorporate it on the homepage, just working out how to do it perhaps more elegantly (yet still prominently) than with bold red text

**Comment by jmlubin** [comment]
It really needs to be there.  What was wrong with the first pass you made at this in red?

**Comment by jesuscript** [comment]
In short, V hated it. Pretty much no other reason... 

Anyway, here's what we'll do: I'll (quietly) put it back for now. Later on this week I'm meeting with our chief "What is Ethereum?" guy (Vinay). We'll try to tackle the broader problem of the homepage not explaining Ethereum very well. Having a tagline definitely helps but doesn't actually solve that problem.

**Comment by jmlubin** [comment]
Sounds good, thanks.

Vinay and I were sitting together when I proposed adding that line and he agreed it was necessary.

What do you think about making it:  
    A peer-to-peer platform for decentralized applications?

**Comment by vbuterin** [comment]
I opposed the way it looked with ugly red text more than the content; the
content is fine. I actually quite liked having "A platform for
decentralized applications" simply be the first of the blue headings that
pops up.

**Comment by jmlubin** [comment]
I thought it was probably a color issue.

My problem with having 
   "A peer-to-peer platform for decentralized applications” 
appear and disappear quickly is that I feel it should be emphasized.  The other blurboids there are lightweight and playful.

Putting that statement upfront, prominently and persistently gives it the importance that it deserves.  Looking at the site from the perspective of someone who is clueless, it would be hard to figure out what ethereum is.  That statement is the crispest way to tell them.

**Comment by jesuscript** [comment]
ok, how's this for a solution: we move "A peer-to-peer ..." down below the twitter feed, where we currently list the features of Ethereum ("Trustless", "Advanced"). Vinay agreed to write a concise (<50 words) answer to to the question "What is Ethereum". We'll have that right underneath the "A peer-to-peer..." headline. Then the list of features will go right below that.

**Comment by jmlubin** [comment]
My preference is to keep it where it is.  It should be the second thing people notice after “ethereum.”  But I am happy to see what you are proposing.

**Comment by jesuscript** [comment]
leaving as is for now
