### ISSUE TITLE
A platform for decentalized applications

### ISSUE THREAD

**Issue by jmlubin** [ethereum/ethereum.org#7]
Instead of having "A platform for decentalized applications" as one of the flashing slogans, it should be persistently placed below the flashing slogans and more prominent and above the three boxes (Development | Ether | Foundation).  It is the crispest answer to the main question: "What is Ethereum?"

**Comment by jesuscript** [comment]
Not sure I understand: do we want multiple blurboids or a single persistent tagline? Or both? https://github.com/ethereum/ethereum.org/issues/6

**Comment by jesuscript** [comment]
sorry, should have read this more carefully. Will be done
